### ISSUE TITLE
Проектирование REST API

### ISSUE THREAD

**Issue by mikhailborodin** [thinknetica-django-lab-03/artyomzhibarev#93]
**Что?**

Изучить правила построения апи по rest архитектуре

**Задачи**

1. Спроектировать апи для своего проекта по rest архитектуре

**Ресурсы**

* https://docs.microsoft.com/ru-ru/azure/architecture/best-practices/api-design

**Comment by artyomzhibarev** [comment]
Я изучил основные подходы построения REST архитектуры
